<?php
$currencys = array(
	'usd' => 'US Dollar (USD)',
	'eur' => 'Euro (EUR)',
	'ron' => 'Romanian (RON)',
	'aud' => 'Australia (AUD)',
	'bgn' => 'Bulgaria (BGN)',
	'cad' => 'Canada (CAD)',
	'cny' => 'China (CNY)',
	'czk' => 'Czech Republic (CZK)',
	'dkk' => 'Denmark (DKK)',
	'hkd' => 'Hong Kong (HKD)',
	'huf' => 'Hungary (HUF)',
	'inr' => 'India (INR)',
	'jpy' => 'Japan (JPY)',
	'nzd' => 'New Zealand (NZD)',
	'nok' => 'Norway (NOK)',
	'pln' => 'Poland (PLN)',
	'rub' => 'Russia (RUB)',
	'sgd' => 'Singapore (SGD)',
	'krw' => 'South Korea (KRW)',
	'sek' => 'Sweden (SEK)',
	'chf' => 'Switzerland (CHF)',
	'twd' => 'Taiwan (TWD)',
	'try' => 'Turkey (TRY)',
	'uah' => 'Ukraine (UAH)',
	'gbp' => 'United Kingdom (GBP)',
);